services:
  cache: 
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: /bin/sh -c "redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD"
    volumes: 
      - cache:/data
    env_file:
      - .env
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    env_file:
      - .env
  zoo:
    image: zookeeper
    restart: always
    hostname: zoo
    ports:
      - 2181:2181
    env_file:
      - .env
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   - node-server
    ports:
      - '4000:80'


volumes:
  db:
    driver: local
  cache:
    driver: local
    